-- Quiz Questions Seed Data
-- Generated: 2025-12-18T00:17:56.895Z
-- Total Questions: 140

-- Clear existing questions
DELETE FROM quiz_questions;

-- Insert questions
INSERT INTO quiz_questions (day_number, order_index, question_text, option_a, option_b, option_c, option_d, correct_answer, explanation)
VALUES
(1, 1, 'What is the primary difference between trading and investing?', 'Trading involves higher amounts of money', 'Trading focuses on short-term price movements for profit', 'Investing is only for professionals', 'There is no difference', 'B', 'Trading focuses on short-term price movements to generate profit, while investing typically involves longer-term positions for growth.'),
(1, 2, 'Which market operates 24/7 without closing?', 'Stock Market', 'Forex Market', 'Cryptocurrency Market', 'Commodities Market', 'C', 'Cryptocurrency markets operate 24/7 without closing, unlike traditional markets that have specific trading hours.'),
(1, 3, 'What does ETF stand for?', 'Electronic Trading Fund', 'Exchange-Traded Fund', 'European Trading Foundation', 'Equity Transfer Fund', 'B', 'ETF stands for Exchange-Traded Fund, which is a basket of securities that trades on an exchange like individual stocks.'),
(1, 4, 'Which market is considered the largest by daily trading volume?', 'Stock Market', 'Forex Market', 'Cryptocurrency Market', 'Commodities Market', 'B', 'The Forex market is the largest financial market by daily trading volume, with over $6 trillion traded daily.'),
(1, 5, 'What is the main risk associated with CFD trading?', 'Limited trading hours', 'High minimum capital requirements', 'Amplified losses due to leverage', 'Inability to trade different markets', 'C', 'CFDs use leverage, which amplifies both gains and losses, making them high-risk instruments that can result in losses exceeding your initial investment.'),
(2, 1, 'What is the main purpose of a demo trading account?', 'To make real profits without risk', 'To practice trading with virtual money and learn platform mechanics', 'To compete with other traders', 'To access premium market data', 'B', 'Demo accounts are designed for risk-free practice, allowing you to learn trading mechanics and platform features without financial consequences.'),
(2, 2, 'Which statement about demo trading is most accurate?', 'Demo success guarantees live trading success', 'Demo trading is completely useless for learning', 'Demo trading builds mechanics and process skills that transfer to live trading', 'Demo accounts always show delayed prices', 'C', 'While demo success doesn'),
(2, 3, 'What is eToro''s standout feature mentioned in the lesson?', 'Lowest fees in the market', 'CopyTrading - automatically replicate successful investors', ',', ',', 'B', 'eToro'),
(2, 4, 'Which platform is described as best for serious traders and professionals?', 'eToro', 'Robinhood', 'Interactive Brokers', 'Trading 212', 'C', 'Interactive Brokers is described as the industry powerhouse with professional-grade tools, global market access, and advanced features for serious traders.'),
(2, 5, 'What should you do in a demo account that you wouldn''t do with real money?', 'Only make safe, conservative trades', 'Avoid learning new features', 'Try risky moves and experiment to understand consequences', 'Focus only on making profits', 'C', 'Demo accounts are perfect for experimenting with risky strategies and testing ideas you'),
(3, 1, 'What is the ''spread'' in trading?', 'The difference between bid and ask price', 'The daily price range', 'The profit from a trade', 'The broker''s commission', 'A', ''),
(3, 2, 'Which order type guarantees execution but NOT price?', 'Limit order', 'Market order', 'Stop limit order', 'Stop loss order', 'B', ''),
(3, 3, 'What does ''going short'' mean?', 'Holding for a short time period', 'Buying small position sizes', 'Selling an asset expecting price to fall', 'Using less leverage', 'C', ''),
(3, 4, 'With 10:1 leverage and £1,000 capital, what position size can you control?', '£100', '£1,000', '£10,000', '£100,000', 'C', ''),
(3, 5, 'What is the PRIMARY purpose of a stop loss order?', 'To guarantee profits', 'To limit potential losses', 'To increase leverage', 'To enter at better prices', 'B', ''),
(4, 1, 'What is the main difference between investing and trading?', 'Investing requires more money than trading', 'Investing is long-term wealth building, trading is short-term profit seeking', 'There is no real difference', 'Trading is safer than investing', 'B', ''),
(4, 2, 'What percentage of day traders are consistently profitable?', '50-60%', '30-40%', '10-20%', '70-80%', 'C', ''),
(4, 3, 'Which analysis method is primarily used by long-term investors?', 'Technical analysis only', 'Fundamental analysis', 'Sentiment analysis', 'No analysis needed', 'B', ''),
(4, 4, 'What is a core-satellite strategy?', 'Trading only technology stocks', '80% long-term investments, 20% active trading', 'Only investing in index funds', 'Day trading with all your capital', 'B', ''),
(4, 5, 'How are long-term investment gains typically taxed compared to short-term trading gains?', 'They are taxed the same', 'Long-term gains have lower tax rates', 'Short-term gains have lower tax rates', 'Neither is taxed', 'B', ''),
(5, 1, 'What does a market index measure?', 'The performance of a section of the stock market', 'Only the largest company in a market', 'The total money in the stock market', 'Government economic policy', 'A', ''),
(5, 2, 'How many companies are in the S&P 500 index?', '30', '100', '500', '1000', 'C', ''),
(5, 3, 'Which index is price-weighted?', 'S&P 500', 'Dow Jones Industrial Average', 'FTSE 100', 'Nasdaq 100', 'B', ''),
(5, 4, 'What is the main advantage of investing in an index fund?', 'Guaranteed profits', 'Automatic diversification across many companies', 'No risk involved', 'Higher returns than individual stocks always', 'B', ''),
(5, 5, 'Which index is considered tech-heavy?', 'Dow Jones', 'FTSE 100', 'Nasdaq 100', 'DAX', 'C', ''),
(6, 1, 'What is the PRIMARY purpose of a stop loss order?', 'To guarantee profits on winning trades', 'To limit potential losses and protect capital', 'To automatically buy more when price drops', 'To increase your leverage ratio', 'B', ''),
(6, 2, 'If you buy a stock at $100 with a stop loss at $95 and take profit at $115, what is your risk-reward ratio?', '1:1', '1:2', '1:3', '2:1', 'C', ''),
(6, 3, 'With 10:1 leverage and £1,000 capital, how much can you control?', '£1,000', '£5,000', '£10,000', '£100,000', 'C', ''),
(6, 4, 'What happens during a margin call?', 'Your broker gives you free money', 'Your leverage automatically increases', 'Your positions are closed if you can''t add more funds', 'Nothing, it''s just a warning', 'C', ''),
(6, 5, 'According to the 1% rule, if you have a £10,000 account, what''s the maximum you should risk per trade?', '£10', '£100', '£1,000', '£5,000', 'B', ''),
(7, 1, 'What does a green/white candlestick body indicate?', 'Price closed higher than it opened (bullish)', 'Price closed lower than it opened (bearish)', 'Price stayed the same all day', 'The stock is ready to crash', 'A', ''),
(7, 2, 'A Hammer candlestick is most reliable when it appears where?', 'At the bottom of a downtrend', 'At the top of an uptrend', 'In the middle of a sideways trend', 'Location doesn''t matter', 'A', ''),
(7, 3, 'What does a Doji candlestick indicate?', 'Strong bullish momentum', 'Strong bearish momentum', 'Indecision between buyers and sellers (open ≈ close)', 'The market is closed', 'C', ''),
(7, 4, 'A Bullish Engulfing pattern consists of:', 'One large green candle', 'Small red candle followed by large green candle that engulfs it', 'Three green candles in a row', 'A candle with no body', 'B', ''),
(7, 5, 'What do long upper and lower wicks on a candlestick indicate?', 'Strong trend continuation', 'Price rejection and volatility at those levels', 'The stock will definitely go up', 'Low trading volume', 'B', ''),
(8, 1, 'What defines a valid uptrend?', 'Series of higher highs and higher lows', 'Series of lower highs and lower lows', 'Price moving sideways', 'Random price movements', 'A', ''),
(8, 2, 'A bull flag pattern indicates what?', 'Trend reversal to the downside', 'Trend continuation to the upside', 'Market will move sideways', 'No predictable movement', 'B', ''),
(8, 3, 'How many points minimum do you need to draw a valid trend line?', '1 point', '2 points', '3 points', '4 points', 'B', ''),
(8, 4, 'What does a Head & Shoulders pattern signal?', 'Bullish continuation', 'Bearish reversal (uptrend ending)', 'Strong uptrend beginning', 'Sideways movement', 'B', ''),
(8, 5, 'What is the most important confirmation for a valid pattern breakout?', 'Price color (green or red)', 'High volume (50%+ above average)', 'Time of day', 'The broker you use', 'B', ''),
(9, 1, 'What does it mean when price is ABOVE the 200 SMA?', 'The long-term trend is bullish/uptrend', 'The long-term trend is bearish/downtrend', 'The stock will crash soon', 'Moving averages don''t indicate trend', 'A', ''),
(9, 2, 'What is the main difference between SMA and EMA?', 'SMA is always more accurate', 'EMA gives more weight to recent prices, reacts faster', 'They are exactly the same', 'EMA can only be used for day trading', 'B', ''),
(9, 3, 'What happens when resistance is broken with high volume?', 'It becomes new support (role reversal)', 'Price will immediately crash', 'Nothing changes', 'Resistance gets stronger', 'A', ''),
(9, 4, 'What makes a support level "strong"?', 'Price only touched it once', 'Multiple touches (3+), high volume, long history', 'It''s a random price level', 'All support levels are equally strong', 'B', ''),
(9, 5, 'What is a "Power Combo" setup in Day 9?', 'Using only one indicator', 'Triple confirmation: Trend (MA) + Level (S/R) + Action (pattern/volume)', 'Trading without stop loss', 'Using as many indicators as possible', 'B', ''),
(10, 1, 'What type of pattern is a Bull Flag, and when does it appear?', 'Continuation pattern that appears mid-uptrend', 'Reversal pattern at top of uptrend', 'Only works in downtrends', 'Reversal pattern at bottom of downtrend', 'A', ''),
(10, 2, 'What does a Head & Shoulders pattern signal?', 'Trend continuation in same direction', 'Bearish reversal - uptrend is exhausted', 'Bullish reversal - downtrend ending', 'No predictable outcome', 'B', ''),
(10, 3, 'How do you calculate the target for a Cup & Handle pattern?', 'Cup depth added to breakout point', 'Handle height added to breakout', 'No mathematical target', 'Always 10% above breakout', 'A', ''),
(10, 4, 'What is the most important confirmation for a pattern breakout?', 'Time of day', 'High volume (50-100%+ above average)', 'Price color (green or red)', 'Pattern size', 'B', ''),
(10, 5, 'What makes a pattern setup "high probability" according to Day 10?', 'Just identifying the pattern correctly', 'Using only one confirmation factor', '5-Point Checklist: Pattern + Trend + MA + S/R + Volume/RR (4-5 checks passed)', 'Trading every pattern you see', 'C', ''),
(11, 1, 'What does RSI below 30 indicate?', 'Oversold condition - potential bounce coming (but check trend first!)', 'Guaranteed buy signal regardless of trend', 'Overbought condition - sell immediately', 'The indicator is broken', 'A', ''),
(11, 2, 'What is the most reliable MACD signal?', 'Every time MACD crosses signal line', 'MACD bullish cross WITH RSI confirmation AND in uptrend', 'Histogram getting bigger', 'MACD is always 100% accurate', 'B', ''),
(11, 3, 'What is "bullish divergence"?', 'Price makes lower low, but RSI/MACD makes higher low (momentum improving)', 'Price and indicators both rising together', 'Price makes higher high, indicators make lower high', 'When all indicators disagree', 'A', ''),
(11, 4, 'How should indicators be interpreted during the Expansion phase of the economic cycle?', 'RSI dips to 30-40 are strong buy signals, MACD crosses work well, buy dips', 'Only short the market during expansion', 'Indicators don''t work in expansion', 'Stay in cash during expansion', 'A', ''),
(11, 5, 'What is the "Triple Confirmation System" for high-probability trades?', 'Using any three indicators randomly', 'MA trend + RSI signal + MACD confirmation + Entry near MA level (all aligned)', 'Only using RSI three times', 'Trading without any confirmation', 'B', ''),
(12, 1, 'What''s the main difference between technical and fundamental analysis?', 'Technical analyzes charts/price, Fundamental analyzes company value/financials', 'They''re the same thing', 'Technical is for stocks, fundamental is for forex', 'Technical is for beginners, fundamental for experts', 'A', ''),
(12, 2, 'What is the Top-Down approach in fundamental analysis?', 'Start with economy → industry → company (broad to specific)', 'Start with company → industry → economy', 'Only analyze companies, ignore economy', 'Focus only on stock charts', 'A', ''),
(12, 3, 'What are the THREE core financial statements?', 'Income Statement, Balance Sheet, Cash Flow Statement', 'P/E ratio, ROE, Debt ratio', 'Charts, Patterns, Indicators', 'Only need income statement', 'A', ''),
(12, 4, 'Where can you find official company financial reports for FREE?', 'SEC EDGAR, Yahoo Finance, company investor relations websites', 'Only paid subscriptions have this data', 'Social media and chat forums', 'Companies keep this information secret', 'A', ''),
(12, 5, 'Why should traders use BOTH technical AND fundamental analysis?', 'Technical shows WHEN to trade (timing), Fundamental shows WHAT to trade (selection)', 'You only need one, not both', 'To confuse yourself with more data', 'Professional traders only use charts', 'A', ''),
(13, 1, 'Company has P/E of 10 while industry average is 20. What does this mean?', 'Stock is potentially undervalued - investors pay less per dollar of earnings', 'Stock is overvalued - too expensive', 'Company is losing money', 'P/E ratio doesn''t matter', 'A', ''),
(13, 2, 'What is the BEST indicator of how efficiently a company uses shareholders'' money?', 'ROE (Return on Equity) - shows profit generated per dollar of equity', 'Stock price', 'Revenue', 'Market cap', 'A', ''),
(13, 3, 'Company has Debt-to-Equity of 3.0. What''s the risk level?', 'HIGH RISK - Company heavily leveraged with too much debt', 'Low risk - very safe', 'Perfect balance', 'Debt doesn''t matter', 'A', ''),
(13, 4, 'Where can you find official company financial statements?', 'SEC EDGAR (10-K annual, 10-Q quarterly reports) - official government filings', 'Only from paid subscriptions', 'Social media tips', 'Company doesn''t share this info', 'A', ''),
(13, 5, 'What''s Warren Buffett''s minimum ROE target?', '20% - He only invests in highly efficient companies', '5%', '50%', 'Buffett doesn''t use ROE', 'A', ''),
(14, 1, 'What is the MINIMUM number of confirmations you should have before taking a trade?', '1 confirmation (just a pattern or indicator)', '2 confirmations (pattern + indicator)', '4+ confirmations (trend + S/R + pattern + indicators + fundamentals + risk plan)', 'No confirmations needed, just trade on gut feeling', 'C', ''),
(14, 2, 'You find a trade setup with 3 confirmations. Entry $100, Stop $95, Target $110. Risk/Reward is 1:2. Should you take this trade?', 'Yes, R:R is 1:2 and you have confirmations', 'No, wait for 4+ confirmations for highest probability', 'Yes, but only if FOMO is driving the decision', 'Yes, ignore confirmations and just trade', 'B', ''),
(14, 3, 'Which is MORE important: winning percentage or following your process?', 'Winning percentage - you must win 80%+ to be profitable', 'Following your process - even with 40-50% win rate, you profit with good risk management', 'Both are equally important', 'Neither matters, just make money somehow', 'B', ''),
(14, 4, 'You''re on Trade #4 and the first 3 trades lost. What should you do?', 'Double your position size to make back losses faster (revenge trading)', 'Stop trading for today - you''re clearly doing something wrong', 'Continue with same risk (1-2%), follow your process, review what went wrong later', 'Remove stop losses to give trades more room', 'C', ''),
(14, 5, 'What''s the PRIMARY goal of today''s simulated trading exercise?', 'Win all 5 trades and make maximum profit', 'Prove you can identify high-quality setups and follow a complete trading process', 'Take as many trades as possible for practice', 'Test different strategies randomly to see what works', 'B', ''),
(15, 1, 'What is the MAXIMUM amount professional traders risk per trade?', '1-2% of account', '5-10% of account', '10-20% of account', 'As much as feels right', 'A', ''),
(15, 2, 'If you lose 50% of your account, what % gain do you need to break even?', '50%', '75%', '100%', '150%', 'C', ''),
(15, 3, 'What is the MINIMUM acceptable risk-reward ratio?', '1:1 (risk $1 to make $1)', '1:2 (risk $1 to make $2)', '1:5 (risk $1 to make $5)', 'No minimum - any ratio works', 'B', ''),
(15, 4, 'Your trade is going against you. What should you do with your stop loss?', 'Move it further away to give trade more room', 'Remove it completely and wait for reversal', 'Keep it exactly where it is - NEVER move against you', 'Double your position to average down', 'C', ''),
(15, 5, 'You have $10,000 account, risk 1%, entry $100, stop $98. How many shares?', '10 shares', '50 shares', '100 shares', 'As many as you can afford', 'B', ''),
(16, 1, 'What is a Golden Cross?', '50 SMA crosses above 200 SMA (super bullish signal)', '20 SMA crosses above 50 SMA', 'Price crosses above any moving average', '50 SMA crosses below 200 SMA', 'A', ''),
(16, 2, 'Which filter is MOST effective at reducing false crossover signals?', 'Only trade crossovers in direction of 200 SMA trend', 'Trade every crossover regardless of trend', 'Only trade on Mondays', 'Ignore volume completely', 'A', ''),
(16, 3, 'Best MA crossover for swing trading (holding days to weeks)?', '5/20 EMA (too fast, many false signals)', '20/50 SMA (balanced, reliable)', '200 SMA only (no crossover)', 'Don''t use MAs for swing trading', 'B', ''),
(16, 4, 'You see a bullish crossover but price is 15% above the fast MA. What should you do?', 'Buy immediately - crossover is always right', 'Skip trade - price overextended, high risk of pullback', 'Short sell instead', 'Use maximum leverage', 'B', ''),
(16, 5, 'Where should stop loss be placed for a long trade entered on bullish 20/50 crossover?', 'Below the 50 SMA (slow MA)', 'Above the 20 SMA (fast MA)', 'No stop loss needed', 'At random price 20% below', 'A', ''),
(17, 1, 'What is the MOST important Fibonacci level (Golden Ratio)?', '61.8% - highest probability reversal level', '50% - psychological level', '23.6% - first retracement', '100% - starting point', 'A', ''),
(17, 2, 'How do you draw Fibonacci for an UPTREND?', 'From swing LOW to swing HIGH (bottom to top)', 'From swing HIGH to swing LOW (top to bottom)', 'From current price to previous price', 'From any point to any point', 'A', ''),
(17, 3, 'What makes a "Triple Confluence" setup so powerful?', '3+ factors align at same price (Fib + S/R + MA) = 75-85% win rate', 'You take 3 trades at the same time', 'Three traders agree on the setup', 'Trade three different assets', 'A', ''),
(17, 4, 'Price breaks below 78.6% Fibonacci level. What does this mean?', 'The trend is likely over - don''t trade this retracement', 'Best buying opportunity - go all in!', 'It''s just a deeper retracement, still bullish', 'Double your position size', 'A', ''),
(17, 5, 'Best confirmation signal to enter at a Fib level?', 'Enter immediately when price touches Fib level', 'Wait for reversal candle pattern + volume spike + RSI confirmation', 'Use gut feeling', 'No confirmation needed with Fibonacci', 'B', ''),
(18, 1, 'What is the MINIMUM number of trades needed for statistical significance in backtesting?', '100+ trades (statistically significant)', '20 trades (enough)', '5 trades (good sample)', 'No minimum needed', 'A', ''),
(18, 2, 'A strategy has 40% win rate but 1:3 risk-reward. Is it profitable?', 'YES - Makes $20 per 10 trades: (4 wins × $30) - (6 losses × $10)', 'NO - Win rate too low', 'Need 60%+ win rate to be profitable', 'Cannot determine without more data', 'A', ''),
(18, 3, 'What is "curve fitting" in backtesting?', 'Over-optimizing strategy to work ONLY on past data (won''t work forward)', 'Drawing trend lines on charts', 'Testing strategy properly', 'Using curved monitors for trading', 'A', ''),
(18, 4, 'What is a good Profit Factor?', 'Above 1.5 (winning $1.50+ for every $1 lost)', 'Below 1.0 (losing system)', 'Exactly 1.0 (breakeven)', 'Doesn''t matter', 'A', ''),
(18, 5, 'After backtesting shows a strategy works, what should you do BEFORE going live?', 'Paper trade for 30 days to confirm results match backtest', 'Go live immediately with full account', 'Skip forward testing - backtest is enough', 'Tell everyone on social media', 'A', ''),
(19, 1, 'What percentage of traders have a written trading plan?', 'Only 10% have written plans', 'About 50% have written plans', 'Most traders (80%) have written plans', 'Plans are not necessary', 'A', ''),
(19, 2, 'What is a realistic annual ROI for an intermediate trader?', '15-30% annual ROI', '200% monthly ROI', '500% annual ROI', '5% annual ROI', 'A', ''),
(19, 3, 'Which of these is the BEST entry rule for a trading plan?', '"Buy when price above 50 MA + RSI below 40 + MACD bullish crossover"', '"Buy when it looks good"', '"Buy when I feel confident"', '"Buy when the news is positive"', 'A', ''),
(19, 4, 'If you start with $10,000 and achieve 2% monthly returns (compounded), what will you have after 1 year?', '~$12,682 (compounded growth)', '$12,400 (simple 24%)', '$11,000', '$10,240', 'A', ''),
(19, 5, 'What should you do after 3 losses in a row according to best practices?', 'Stop trading for the day (circuit breaker)', 'Double your position size to recover losses', 'Switch to a different strategy immediately', 'Keep trading - losses are normal', 'A', ''),
(20, 1, 'What percentage of trading success is attributed to psychology vs technical knowledge?', '80% psychology, 20% technical', '50% psychology, 50% technical', '20% psychology, 80% technical', '100% technical knowledge', 'A', ''),
(20, 2, 'After losing 2 trades in a row, what should you do?', 'Double position size to recover losses', 'Stop trading for the day', 'Switch to a different strategy', 'Trade more to make it back', 'B', ''),
(20, 3, 'Which emotional state is BEST for trading?', 'Euphoric and excited', 'Angry and determined', 'Neutral to confident', 'Fearful and cautious', 'C', ''),
(20, 4, 'What''s more important: Financial capital or Psychological capital?', 'Financial capital only matters', 'Psychological capital is more important', 'Neither matters if you have a good strategy', 'Only financial capital can be measured', 'B', ''),
(20, 5, 'When you miss a big move in a stock, what should you do?', 'Chase it immediately before it goes higher', 'Wait for the next setup opportunity', 'Increase position size on the next trade', 'Get angry at yourself for missing it', 'B', ''),
(21, 1, 'A stock costs $50 and pays $2 annual dividend. What''s the dividend yield?', '4%', '2%', '25%', '$2', 'A', ''),
(21, 2, 'Which bond type has the LOWEST risk?', 'High-yield corporate bonds', 'Government treasury bonds', 'Junk bonds', 'Startup company bonds', 'B', ''),
(21, 3, 'What''s a dangerous dividend payout ratio?', '30%', '50%', 'Over 100%', 'Under 20%', 'C', ''),
(21, 4, 'What happens to bond prices when interest rates rise?', 'Bond prices increase', 'Bond prices decrease', 'No effect on prices', 'Bonds become stocks', 'B', ''),
(21, 5, 'What is DRIP?', 'Dividend Reinvestment Plan', 'Daily Risk Investment Protocol', 'Declining Rate Interest Program', 'Direct Return Investment Platform', 'A', ''),
(22, 1, 'What percentage of your portfolio should you risk on IPO day one trades?', 'Maximum 1% of portfolio', '10-20% is fine', '50% for big opportunities', 'All in if you believe', 'A', ''),
(22, 2, 'What percentage of penny stocks typically go to zero?', '10%', '50%', '90-95%', '25%', 'C', ''),
(22, 3, 'When scalping, what''s the recommended profit target per trade?', '10-20%', '0.5-2%', '5-10%', 'Hold until 50%+', 'B', ''),
(22, 4, 'What VIX level indicates extreme market fear/volatility?', 'Under 15', '15-25', 'Above 30-35', 'Exactly 20', 'C', ''),
(22, 5, 'What''s the maximum recommended total portfolio allocation to volatile markets (IPOs, penny stocks, crypto combined)?', '5-10%', '25%', '50%', 'As much as you want', 'A', ''),
(23, 1, 'What is the typical minimum investment for hedge funds?', '$1,000', '$10,000', '$1 million+', 'No minimum', 'C', ''),
(23, 2, 'What risk score should you look for when copy trading?', '1-2 (too conservative)', '3-5 (moderate)', '7-10 (high risk)', 'Risk doesn''t matter', 'B', ''),
(23, 3, 'How long should a trader be active before you consider copying them?', '1 week', '1 month', '2+ years', 'Time doesn''t matter', 'C', ''),
(23, 4, 'What''s the maximum drawdown you should accept from a copied trader?', 'Under 20%', '30-40%', '50%+', 'Any amount', 'A', ''),
(23, 5, 'How long should you practice copy trading on demo before using real money?', '1 week', '1 month', '6+ months minimum', 'Start with real money immediately', 'C', ''),
(24, 1, 'How much MORE do rebalanced portfolios typically earn annually?', '0.5%', '1.5%', '5%', '10%', 'B', ''),
(24, 2, 'What is the classic balanced portfolio allocation?', '80% Stocks, 20% Bonds', '60% Stocks, 40% Bonds', '50% Stocks, 50% Bonds', '40% Stocks, 60% Bonds', 'B', ''),
(24, 3, 'What is the recommended threshold drift percentage for moderate rebalancing?', '5%', '10%', '15%', '20%', 'B', ''),
(24, 4, 'What does rebalancing help you do automatically?', 'Buy high and sell low', 'Buy low and sell high', 'Maximize risk exposure', 'Avoid all market losses', 'B', ''),
(24, 5, 'Which rebalancing method combines time-based and threshold-based triggers?', 'Calendar Method', 'Threshold Method', 'Hybrid Method', 'Dynamic Method', 'C', ''),
(25, 1, 'What percentage of traders who track performance are profitable?', '10%', '35%', '65%', '90%', 'C', ''),
(25, 2, 'What is a good Profit Factor range?', 'Below 1.0', 'Above 1.5', 'Exactly 1.0', 'Above 5.0', 'B', ''),
(25, 3, 'What is the maximum acceptable drawdown for most traders?', '5%', '20%', '50%', '75%', 'B', ''),
(25, 4, 'How often should you review your trading performance?', 'Once a year', 'Weekly and monthly', 'Never', 'Every hour', 'B', ''),
(25, 5, 'What should you track in your trading journal?', 'Only winning trades', 'Only profit/loss numbers', 'Everything: setup, entry, exit, emotions, lessons', 'Nothing, just trade', 'C', ''),
(26, 1, 'What percentage of your strategies typically produce most of your profits?', '20% produce 80% of profits', '50% produce 50% of profits', '80% produce 20% of profits', 'All strategies equal', 'A', ''),
(26, 2, 'When testing strategy adjustments, how should you proceed?', 'Change everything at once', 'Change one variable at a time', 'Never make adjustments', 'Random changes', 'B', ''),
(26, 3, 'How many trades should you test before eliminating a strategy?', '5 trades', '10 trades', '50+ trades', '1 trade', 'C', ''),
(26, 4, 'If data shows you lose after 3 trades per day, what should you do?', 'Trade more to practice', 'Limit yourself to 2-3 trades maximum', 'Ignore the data', 'Stop trading completely', 'B', ''),
(26, 5, 'How long should you test adjustments on demo before considering them validated?', '1 week', '1 month', 'At least 3 months', '1 day', 'C', ''),
(28, 1, 'Which indicator is released on the first Friday of each month?', 'GDP', 'CPI', 'NFP (Non-Farm Payrolls)', 'Interest Rates', 'C', ''),
(28, 2, 'What happens to currency when interest rates increase?', 'Currency strengthens (goes up)', 'Currency weakens (goes down)', 'No effect', 'Random movement', 'A', ''),
(28, 3, 'What is the central bank''s typical inflation target?', '0%', '2%', '5%', '10%', 'B', ''),
(28, 4, 'How many quarters of negative GDP indicate a recession?', '1 quarter', '2 consecutive quarters', '3 quarters', '4 quarters', 'B', ''),
(28, 5, 'What should you do before high-impact news?', 'Increase position size', 'Reduce or close positions', 'Add more leverage', 'Ignore the news', 'B', ''),
(29, 1, 'What does the ''M'' in SMART goals stand for?', 'Manageable', 'Measurable', 'Meaningful', 'Motivated', 'B', ''),
(29, 2, 'What''s a realistic monthly return goal for new traders?', '50-100%', '20-30%', '3-5%', '0%', 'C', ''),
(29, 3, 'How often should you review your trading goals?', 'Weekly review, monthly adjustment', 'Once a year', 'Never change them', 'Daily changes', 'A', ''),
(29, 4, 'What increases goal achievement rate to 95%?', 'Thinking about goals', 'Writing goals down', 'Regular accountability', 'Keeping goals secret', 'C', ''),
(29, 5, 'How long minimum should you stay on demo?', '1 month', '3 months', '6 months minimum', 'No minimum', 'C', '');
